"""Add user_id to transaction

Revision ID: 06ad2cc8d61e
Revises: ee72599c1878
Create Date: 2025-04-13 12:42:38.501291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ad2cc8d61e'
down_revision = 'ee72599c1878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_transaction_user_id', 'user', ['user_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
